version: 2


models:
  - name: stg_issues
    description: >
      Contains issues by users to various GitHub repos
    columns:
      - name: id
        description: "Unique identifier for the issue."
        data_tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: owner
        description: "Owner of the repository."
      - name: repo
        description: "Name of the repository."
      - name: number
        description: "Number of the issue within the repository."
      - name: title
        description: "Title of the issue."
      - name: state
        description: "Current state of the issue (e.g., open, closed)."
      - name: created_at
        description: "Timestamp when the issue was created."
      - name: updated_at
        description: "Timestamp when the issue was last updated."
      - name: closed_at
        description: "Timestamp when the issue was closed."
      - name: comments
        description: "Number of comments on the issue."
      - name: draft
        description: "Indicator if the issue is a draft."
      - name: author_association
        description: "Author's association with the repository."
      - name: user_id
        description: "Identifier for the user who created the issue."
      - name: label_id
        description: "Identifier for the primary label associated with the issue."
      - name: repository_url
        description: "URL of the repository the issue belongs to."
      - name: total_count
        description: "Total number of reactions on the issue."
      - name: plus1
        description: "Number of +1 reactions on the issue."
      - name: minus1
        description: "Number of -1 reactions on the issue."
      - name: laugh
        description: "Number of laugh reactions on the issue."
      - name: hooray
        description: "Number of hooray reactions on the issue."
      - name: confused
        description: "Number of confused reactions on the issue."
      - name: heart
        description: "Number of heart reactions on the issue."
      - name: rocket
        description: "Number of rocket reactions on the issue."
      - name: eyes
        description: "Number of eyes reactions on the issue."
      - name: response
        description: "The raw json string."
      - name: load_date
        description: "Load date."
  
  - name: stg_raw_issues
    description: >
      Contains raw issues by users to various GitHub repos
    columns:
      - name: id
        description: "Unique identifier for the issue."
        data_tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: response
        description: "Raw json response"
      - name: created_at
        description: "Date of issue creation.s"